preload = $HOME/Wallpapers/night-race.png

# wallpaper = HDMI-A-1,$HOME/Wallpapers/night-race.png
# wallpaper = eDP-1,$HOME/Wallpapers/night-race.png

wallpaper {
    monitor = HDMI-A-1
    path = $HOME/Wallpapers/rbr-1.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = $HOME/Wallpapers/rbr-1.png
    fit_mode = cover
}
    
splash = false