exec-once = systemctl --user start hyperpolkitagent
exec-once = nm-applet
exec-once = hyprpaper --config ~/.config/hypr/hyprpaper.conf
exec-once = waybar
exec-once = swaywc
exec-once = hyprlauncher -d
exec-once = ~/.local/bin/clipboard-clear
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = playerctld daemon
