#!/bin/bash

STATUS=$(playerctl status 2>/dev/null)

case "$STATUS" in
  Playing)
    echo '{"text":"󰎈","tooltip":"Media playing"}'
    ;;
  Paused)
    echo '{"text":"󰏤","tooltip":"Media paused"}'
    ;;
  *)
    echo '{"text":""}'
    ;;
esac