#!/bin/bash

ID=91190

case "$1" in
  up)
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
    ;;
  down)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    ;;
  mute)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    ;;
esac

STATUS="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
VOLUME="$(echo "$STATUS" | awk '{print int($2 * 100)}')"

if echo "$STATUS" | grep -q MUTED; then
  notify-send -r "$ID" -t 900 -u low -a "Volume OSD" -h string:x-canonical-private-synchronous:volume -h string:synchronous:volume -h int:transient:1 -h int:value:0 "󰝟 Volume" "Muted"
else
  notify-send -r "$ID" -t 900 -u low -a "Volume OSD" -h string:x-canonical-private-synchronous:volume -h string:synchronous:volume -h int:transient:1 -h int:value:"$VOLUME" "󰕾 Volume" "$VOLUME%"
fi
