#!/bin/bash

DIR="$HOME/Pictures/Screenshots"
FILE="$DIR/$(date +%Y-%m-%d_%H-%M-%S).png"

mkdir -p "$DIR"
grim "$FILE" || exit 1
pw-play "$HOME/.config/hypr/sounds/screenshot-shutter.wav"

ACTION=$(notify-send -i "$FILE" -A open="Open Folder" "📷 Screenshot Saved" "Saved to Screenshots")
[ "$ACTION" = "open" ] && ${FILE_MANAGER:-dolphin} "$DIR" &
